export const ONBOARDING_STEPS = [
  {
    id: 'primary_goal',
    field: 'primary_goal',
    title: "What's your primary fitness goal?",
    subtitle: 'This shapes everything I recommend for you.',
    hint: 'e.g. lose weight, build muscle, run a 5K, get more active, reduce stress',
    type: 'textarea',
    required: true,
    options: [
      'Lose weight',
      'Build muscle',
      'Run a 5K',
      'Get more active',
      'Reduce stress',
      'Improve mobility',
      'Train for an event',
    ],
  },
  {
    id: 'secondary_goal',
    field: 'secondary_goal',
    title: 'Do you have a secondary goal?',
    subtitle: 'Optional — but it helps me balance your plan.',
    hint: 'e.g. mainly lose weight, but also want to get stronger',
    type: 'textarea',
    required: false,
    options: ['Get stronger', 'Improve endurance', 'Better flexibility', 'More energy'],
  },
  {
    id: 'equipment',
    field: 'equipment',
    title: 'What equipment do you have access to?',
    subtitle: 'Pick all that apply or describe your setup.',
    type: 'chips-multi',
    required: true,
    options: [
      'Full gym',
      'Home dumbbells',
      'Barbell + rack',
      'Bodyweight only',
      'Resistance bands',
      'Kettlebells',
      'Pull-up bar',
      'Cardio machines',
    ],
  },
  {
    id: 'days_per_week',
    field: 'days_per_week',
    title: 'How many days per week can you realistically work out?',
    subtitle: 'Be honest — 3 consistent days beats 6 days you\'ll skip.',
    type: 'chips-single',
    required: true,
    options: ['1', '2', '3', '4', '5', '6', '7'],
  },
  {
    id: 'workout_duration_minutes',
    field: 'workout_duration_minutes',
    title: 'How long can each workout be?',
    subtitle: 'I\'ll design sessions that fit your schedule.',
    type: 'chips-single',
    required: true,
    options: ['20', '30', '45', '60'],
    optionLabels: { '20': '20 min', '30': '30 min', '45': '45 min', '60': '60 min' },
  },
  {
    id: 'preferred_workout_time',
    field: 'preferred_workout_time',
    title: 'What time of day do you prefer to work out?',
    subtitle: 'This affects what I schedule for you.',
    type: 'chips-single',
    required: true,
    options: ['Morning', 'Lunch', 'Evening', 'Flexible'],
  },
  {
    id: 'injuries_limitations',
    field: 'injuries_limitations',
    title: 'Any injuries, limitations, or movements to avoid?',
    subtitle: 'Your safety comes first — I\'ll never ask again unless you tell me something changed.',
    hint: 'Leave blank if none',
    type: 'textarea',
    required: false,
    options: ['None', 'Knee issues', 'Lower back', 'Shoulder pain', 'Wrist/elbow'],
  },
  {
    id: 'fitness_level',
    field: 'fitness_level',
    title: "What's your current fitness level?",
    subtitle: 'No judgment — this helps me calibrate intensity.',
    type: 'chips-single',
    required: true,
    options: ['Complete beginner', 'Beginner', 'Intermediate', 'Advanced'],
  },
  {
    id: 'exercises_hate',
    field: 'exercises_hate',
    title: 'Any types of exercise you hate?',
    subtitle: 'I\'ll steer clear so you actually stick with it.',
    hint: 'e.g. burpees, long runs, HIIT',
    type: 'textarea',
    required: false,
    options: ['Burpees', 'Long runs', 'HIIT', 'Heavy lifting', 'Cardio machines'],
  },
  {
    id: 'exercises_love',
    field: 'exercises_love',
    title: 'Any types of exercise you love?',
    subtitle: 'I\'ll weave these in whenever it makes sense.',
    hint: 'e.g. cycling, yoga, swimming',
    type: 'textarea',
    required: false,
    options: ['Running', 'Cycling', 'Yoga', 'Swimming', 'Strength training'],
  },
]

export function buildConfirmationMessage(answers) {
  const limitations = answers.injuries_limitations?.trim() || 'no major limitations'
  const duration = answers.workout_duration_minutes
  return `Got it. You want to ${answers.primary_goal}, you have ${answers.equipment}, you can do ${answers.days_per_week} days a week for ${duration} minutes, and you're at the ${answers.fitness_level} level. I'll avoid ${limitations}. Let's go.`
}
